require 'sensu-plugins-azurerm/common'
require 'sensu-plugins-azurerm/compute_usage'
require 'sensu-plugins-azurerm/network_usage'
require 'sensu-plugins-azurerm/servicebus_usage'
require 'sensu-plugins-azurerm/version'
